- name: Configure EKS nodes
  hosts: eks_nodes
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install monitoring agent
      apt:
        name: datadog-agent
        state: present
      when: ansible_os_family == "Debian"

    - name: Start and enable Datadog agent
      systemd:
        name: datadog-agent
        state: started
        enabled: yes

    - name: Apply security patches
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"
